### ISSUE TITLE
Transaction Details Not Found

### ISSUE THREAD

**Issue by sdefi** [ava-labs/ortelius#104]
I created a test on mainnet wallet to send 1 avax which worked

I copied new wallet address to send some more tokens and the tx failed or is stuck.

txid: RngE3Ue9rANeJ6ob32Li11kN7eRwo6S8EA5obJYLzSTiYhr3Z

https://explorer.avax.network/tx/RngE3Ue9rANeJ6ob32Li11kN7eRwo6S8EA5obJYLzSTiYhr3Z

**Comment by tasinco** [comment]
What do you mean the tx is failed or stuck?  Is this from: https://docs.avax.network/v1.0/en/api/avm/#avmgettxstatus

**Comment by sdefi** [comment]
I withdrew a single AVAX from okex. The single avax arrived, then I tried to send the rest and the transaction was completed at okex end but when I clicked the tx link (as above) that's the error I get. Tokens still have not arrived. I had a chat to okex they said they've sent the tokens but the issue is at avalanche end.

Then when I clicked the (submit issue) from the link above it brought me here.

**Comment by tasinco** [comment]
'and the transaction was completed at okex end'

If the transaction was completed, then it would of transmitted onto the network, and all nodes would be updated. 

There is no record of txid: RngE3Ue9rANeJ6ob32Li11kN7eRwo6S8EA5obJYLzSTiYhr3Z on explorer, which means it did not actually complete.

The status of RngE3Ue9rANeJ6ob32Li11kN7eRwo6S8EA5obJYLzSTiYhr3Z needs to be checked on the node that sent the Tx.  If the Tx is in the state of Processing, it did not actually complete.  If you re-submit the Tx bytes you should get notified of the reason it didn't actually Process.

**Comment by tasinco** [comment]
after speaking with OKEX the problem looks resolved.  The txid: RngE3Ue9rANeJ6ob32Li11kN7eRwo6S8EA5obJYLzSTiYhr3Z is now visible in the explorer.

**Comment by sdefi** [comment]
Thanks for assisting promptly. The issue was at okex end.

I would suggest diverting the user to another support page instead of github in future. Some issues do not need to be public.
