### ISSUE TITLE
Cache collisions on requests with time params

### ISSUE THREAD

**Issue by tyler-smith** [ava-labs/ortelius#107]
Design bug. 

Because startTime/endTime have so many potential valid values we round the time *for the cache key only* to 15s intervals in an attempt to reduce the surface area for blowing up the cache. This was done originally when our only time params were for the aggregates endpoint where the slight inprecision is tolerable but we now use these params for ListTransactions and potentially others in the future and this becomes a noticeable issue.

Specifically a request with startTime=0 will cache results for that value but subsequent requests for e.g. startTime=14 will show the old results for 5 minutes. After that a request for startTime=14 will now cache those results which will collide with startTime 0-13.

**Comment by tasinco** [comment]
We cache to the [hour](https://github.com/ava-labs/ortelius/blob/75c192ef0133c38670c823d8ef52e46b32e5dce4/services/indexes/params/collections.go#L213)

But we query for [exact provided time](https://github.com/ava-labs/ortelius/blob/75c192ef0133c38670c823d8ef52e46b32e5dce4/services/indexes/params/collections.go#L253)

And we store in cache for [5 seconds](https://github.com/ava-labs/ortelius/blob/9ca36255ffdeb976226fa2ee698cf16e46dcf715/services/indexes/avm/api.go#L131)

There has to be a happy middle.  Maybe round up to 5 seconds?
I do think 5 seconds in cache seems fine.
