### ISSUE TITLE
TPS calculation

### ISSUE THREAD

**Issue by ekherit** [ava-labs/ortelius#23]
Hello!

Last 36 hours I was sending transactions with average rate of around 30 TPS with following way. I created 10k users at gecko node then fund 5k users and started to send 1nAVA  from first 5k users to second 5k users. So many users are intended not to wait transaction confirmation after single send.  But explorer shows only 2 TPS for last 24 hours. 
![explorer-tps2](https://user-images.githubusercontent.com/2533826/87242468-16af2f80-c457-11ea-8da8-d7665de81c9e.png)

Is there some problem or not? Or I did something wrong. For each user I send transaction if previous one for this user was Accepted.

**Comment by tyler-smith** [comment]
There were issues before ingesting transactions at this scale. We have made a number of optimizations here with some successful throughput tests. I am closing this and if issues reoccur here we can re-open.
