### ISSUE TITLE
Transaction Details Not Found: AcHrhZQFHnAkbp5U4LmbpjjUnSFAZqnDcLwNr54NYJo8WAbjU 

### ISSUE THREAD

**Issue by s3cryptostuff** [ava-labs/ortelius#230]
A transfer from binance seems to have gone nowhere:
Has been processing since 2020-12-23 12:00:40 

Transaction Details Not Found
A record for this transaction ID was not found in the Avalanche Explorer

AcHrhZQFHnAkbp5U4LmbpjjUnSFAZqnDcLwNr54NYJo8WAbjU

**Comment by tasinco** [comment]
You will need to contact binance support.

**Comment by s3cryptostuff** [comment]
thanks
