### ISSUE TITLE
Binance withdrawal pending

### ISSUE THREAD

**Issue by sglod** [ava-labs/ortelius#233]
I initiated a withdrawal from Binance but the transaction never materialized and it still says processing on the Binance website.
TxID: 2wQpkJ52L3Ss9F6say2zwGXA5d6mZUwPd7R1av9MyYJagGGi5P

What can I do?

**Comment by tasinco** [comment]
The ortelius team does not have control of how transactions are created and managed by exchanges.  You need to reach out to the exchange for assistance.
