### ISSUE TITLE
Axav ; Transaction Details Not Found

### ISSUE THREAD

**Issue by fcertel** [ava-labs/ortelius#266]
I did to times whitdraw avax from Paribu to TRBinance. Transaction Details Not Found
A record for this transaction ID was not found in the Avalanche Explorer
1. 2DTi9ernZWF1Y7wXQp6MBAirxhS5CejQuJpMcENcxBaGjcXFwF

2. 2Qvymv7WmAfAFf3v3TxEFRCY1TBpr6Nu9Q7NBMdxrGmuBJ2rVg

Can you help me?

**Comment by frkglr** [comment]
I have the exact problem 
txID: deVacqCmWEG524gHZkjtTPn6Fsv3b6TCaL3zTM5vNBdK6NPaZ

**Comment by eren-c** [comment]
same
2kyPiJdGkYLskNEXPyYX6f5iMBy9m2ZW1z6HGhoyWvJmbHxEyP

**Comment by frkglr** [comment]
Sorunlarınız çözüldü mü? Paribu'dan birisine ulaşabildiniz mi?

**Comment by gurkan7** [comment]
Bu sorunu ben de yaşadım. 11.51 itibariyle. Paribu dan kimse de geri dönmedi.

A record for this transaction ID was not found in the Avalanche Explorer. 

My4EW8Tx78JaxZWBWV4GpEy3kPLs1AZnubPvHFd4apGzC7wkf

**Comment by eren-c** [comment]
paribu dönüş yaptı çözecekleri şeklinde mail attılar ama değişen birşey yok

frkglr <notifications@github.com>, 9 Oca 2021 Cmt, 14:29 tarihinde şunu
yazdı:

**Comment by fcertel** [comment]
Benim sorunum çözüldü, destek kaydımı sabah 7 de açmıştım , öğlen 2 gibi birden farkettimki avaxlar hesabıma iade olmuş. Şans eseri gördüm dönüpte mail atmadılar. Sonra sattım kurtuldum.

**Comment by eren-c** [comment]
benimkide az önce iade oldu.

fcertel <notifications@github.com>, 9 Oca 2021 Cmt, 18:19 tarihinde şunu
yazdı:

**Comment by tasinco** [comment]
The explorer is only able to show transactions that have been accepted by the network.
You will need to work with the exchanges.
