### ISSUE TITLE
Avax trasnfer

### ISSUE THREAD

**Issue by eren-c** [ava-labs/ortelius#267]
I did to times whitdraw avax from Paribu to Binance (January 8 ,14:33) . the transfer hasn't happened yet. A lot of time has passed since. 

Transaction Details Not Found

A record for this transaction ID was not found in the Avalanche Explorer

2kyPiJdGkYLskNEXPyYX6f5iMBy9m2ZW1z6HGhoyWvJmbHxEyP

Can you help me?

**Comment by tasinco** [comment]
The explorer is only able to show transactions that have been accepted by the network.
You will need to work with the exchanges.
