### ISSUE TITLE
Missed output with `indexOutput = 0` on token AVA

### ISSUE THREAD

**Issue by menxit** [ava-labs/ortelius#28]
Seems genesis transaction of AVA doesn't return output with `indexOutput = 0`:
- https://explorerapi.avax.network/x/transactions/21d7KVtPrubc5fHr6CGNcgbUb4seUjmZKr35ZX7BZb5iP8pXWA

**Comment by tyler-smith** [comment]
This was an issue on Denali. It has been fixed before Everest.
