### ISSUE TITLE
failed to load resource

### ISSUE THREAD

**Issue by liuxh-go** [ava-labs/ortelius#283]
I started the node using docker-compose, and then there were two problems when requesting the api

* some transactions could not get transaction information
* after the node was running for a period of time, the request interface returned the following error:
```
{
    "code": 500,
    "message": "failed to load resource"
}
```

**Comment by liuxh-go** [comment]
The request api cannot obtain the transaction data with the transaction ID `2ZzCUKrHrZWC4GNgiox7mTC1PnnBwNshcM9CD37dKEyJcy7EKR`

**Comment by liuxh-go** [comment]
I can see the address avax1qgkufg7w3r8xvm7gwyxmkfgdja54elxhdap834 on the browser, but the relevant information cannot be obtained by calling the api query

**Comment by tasinco** [comment]
You can review the docker logs for any errors.

**Comment by liuxh-go** [comment]
I updated the docker image and now this problem is solved.

But now there is a new problem. I call the `avm.issueTx` method to send a transaction, and the transaction id is `nY2sJJn4T4uVZbmnweE5VfjxUarfvThxrHBq5eJfHtQ8uHGCn`, call `avm.getTxStatus` method to see that the transaction status is `Accepted`. but I visit `http://xxx:xxx/v2 /transactions/nY2sJJn4T4uVZbmnweE5VfjxUarfvThxrHBq5eJfHtQ8uHGCn` but no transaction information was found.

 I checked the log of `production_indexer_1` and only found this piece of relevant information: 
```
[2021-01-20T06:06:49.838103433Z]: job:index-consensus event:dbr.exec time:286 μs kvs:[chain_id:2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzFBQ5s3qs3qs3qs3 WPkp1jptZB1ssNKqf6j5WKKsGSpjp74ormkXmW6Y2zaLF3gVh sql: INSERT INTO `transactions_epoch` (` id`, `epoch`,` vertex_id`) VALUES ( 'nY2sJJn4T4uVZbmnweE5VfjxUarfvThxrHBq5eJfHtQ8uHGCn', 0, 'WPkp1jptZB1ssNKqf6j5WKKsGSpjp74ormkXmW6Y2zaLF3gVh')]
```

How can i solve this problem? @tasinco

**Comment by tasinco** [comment]
Running a single ortelius instance, it is possible that that transactions could get lost. Our production setup we run a shared database and kafka instance with multiple ortelius producers and indexers for redundancy.
The default provided docker images will not configure your system like this, and it would require more extensive setup and resources to run properly and have redundancy. It will also require a significant level of devops knowledge to manage and run.
Should the ortelius instance be down or having issues during your issueTx you could of lost the tx.  It will not be re-processed.

The logging message you attached is from processing the consensus records, not the decision records.  It is not clear what was going on in your setup at the time of the tx based on the information you provided.

I can only assume that this tx: https://explorer.avax.network/tx/nY2sJJn4T4uVZbmnweE5VfjxUarfvThxrHBq5eJfHtQ8uHGCn is yous.  And as you can see our production nodes successfully parsed the message.

You could take down your ortelius instance and have it re-build from scratch that should reprocess all the transactions locally.

And always be sure to upgrade your code base to the most recent master branch.
