### ISSUE TITLE
May the ortelius call an http api on X chain transactions

### ISSUE THREAD

**Issue by tontonq** [ava-labs/ortelius#287]
Hi i was opened same issue  for avalanchego too but not sure if it get considered,
can such feature could be done?
When an successful transfer that has been accepted by the network has been done on x chain ,
node will post the details to an http api can be speficied by cmd arg .

ortelius stream callbacker -c path/to/config.json
in the config file
`"networkID": 1,
"callback_http": "http://127.0.0.1:8080",
`
and ortelius will post something like that to our endpoint

```
POST http://127.0.0.1:8888/new_transaction HTTP/1.1
Host: 127.0.0.1
Content-Length: 1056
Content-Type: application/json

{
    "transaction_id": "2KwLJBZXsNa9tDgZbJix1DfYBBfmTRmqnyT4nPZk2n1HDntai",

    "inputs": [{
            "input_address": "avax1lmfwfq68f5autmpdx0j0ag3mvr94dqjr9ptjks",
            "asset_id": "FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z",
            "amount": 100223
        }, {
            "input_address": "avax1wdpn22pu2qaud9uxca4hdj5e90t6grk064xn49",
            "asset_id": "FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z",
            "amount": 200000
        }
    ],

    "outputs": [{
            "output_address": "avax1llaexasqcmlpsn3l254pzrf5qu8gqun323xgcx",
            "asset_id": "FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z",
            "amount": 100223
        }, {
            "output_address": "avax1l3dv3vrk0l8pjyhysz8kv354s6aqxw4nlmv0yl",
            "asset_id": "FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z",
            "amount": 200000
        }
    ],

}

```

currently the all exchanges and other websites are regularly scanning defined addresses of user's for new utxos, this is why it exchange sites takes time to credit users , we need something better to notify the backends , without it users needs wait uncertain time,so it makes avax coin slower even the slowest blockchains , even if it doesnt meet your roadmap, i would kindly ask the filename writes the new transactions to the mysql db , maybe i can find a way to do it somehow

**Comment by tasinco** [comment]
This will not be implemented in ortelius.
There is work in progress to offer a feature on the avalanchego node to subscribe tx's from certain addresses.
