### ISSUE TITLE
Ortelius missing transactions 

### ISSUE THREAD

**Issue by sollover** [ava-labs/ortelius#289]
hi everyone,

I updated the my avalanchego node approximate 10 days before to avalanche go 1.1.1.  But the ortelius missing quite a lot the transactions. (some transactions there aren't in ortelius, -ortelius didn't index its-) It's missing before versions (1.0 and 1.1) too, but not this much. I'm thinking return to avalanche 1.0. (first version). or what can I do else? I guess, if I update the avalanchego to 1.1.4, this problem will continue again :(

thank you

**Comment by tasinco** [comment]
It is unclear how you have ortelius setup to run based on your description.  If you run ortelius with docker it will start up a avalanchego node, and of the master branch that node is 1.1.3 however it 1.1.4 is a minor update and will work just as well.
Running a single ortelius instance, it is possible that that transactions could get lost.  Our production setup we run a shared database and kafka instance with multiple ortelius producers and indexers for redundancy.
The default provided docker images will not configure your system like this, and it would require more extensive setup and resources to run properly and have redundancy.  It will also require a significant level of devops knowledge to manage and run.
Downgrading your node is not recommended, and with upcoming releases will more than likely render them inoperable.

**Comment by sollover** [comment]
I used your last docker image (published) for ortelius(https://github.com/ava-labs/ortelius - I used directly this.). It works **avalanchego:v1.1.3** but it's missing a lot transactions still... Also ortelius running on 15GB space and the system  has free space -generally- approximate 5GB... is this not enough?  what is the ideal resource -requirements- for ortelius run properly?? @tasinco

**Comment by tasinco** [comment]
There is an infinite amount of space needed to run ortelius for the future.  It will constantly consume an index transactions and grow.

In general our production systems run in aws using an aurora db and a managed kafka instance.  We also run dual instances of ortelius consuming from 2 different nodes for redundancy.

Without that type of setup it is possible to lose transactions.  This is not the standard docker image setup and requires additional devops resources to manage and maintain.

To help mitigate any loss make sure kafka is booted up and topics have been crated.  And db is up and tables have been created before starting the producer and indexer.
