### ISSUE TITLE
Missed transaction

### ISSUE THREAD

**Issue by menxit** [ava-labs/ortelius#31]
As you can see this address returns:
https://explorerapi.avax.network/x/addresses/gbAzVifoVBeUDQYNptfdeMkZCimxShZz

- totalReceived: 2000 
- totalSent: 20000

However, `/x/transactions` returns only a received transaction (and not even a sent one):
https://explorerapi.avax.network/x/transactions?address=gbAzVifoVBeUDQYNptfdeMkZCimxShZz

There is another example of missed transaction. Let's take this transaction:
https://explorerapi.avax.network/x/transactions/2fvcavmcBd4JvE7WYzGMMuSnjKwSmeRCnDoqZ1KsnPE82M3tVt

As you can see this transaction uses as input an output generated in this transaction 2sHJpXEXdoVzcsX3cqYBj53gKbDRzyyaVLXVWabAbKwqkzwUEZ, that seems to miss: 
https://explorerapi.avax.network/x/transactions/2sHJpXEXdoVzcsX3cqYBj53gKbDRzyyaVLXVWabAbKwqkzwUEZ

**Comment by fabiux82** [comment]
This is an other example of missing transaction:

https://explorerapi.avax.network/x/transactions/2V4B4YRf5BT2c6qL9D7c6ZLPPP2Z575ECovainxXf2aG78mnNq
The input consumed refer to txid: 2sHJpXEXdoVzcsX3cqYBj53gKbDRzyyaVLXVWabAbKwqkzwUEZ

But tx api returns null:
https://explorerapi.avax.network/x/transactions/2sHJpXEXdoVzcsX3cqYBj53gKbDRzyyaVLXVWabAbKwqkzwUEZ

**Comment by tyler-smith** [comment]
We have diagnosed and fixed issues with dropped transactions. If new issues are found we'll create a new issue.
