### ISSUE TITLE
Addresses without sent transactions can't be retrieved

### ISSUE THREAD

**Issue by menxit** [ava-labs/ortelius#32]
As you can see this url returns `null`:
https://explorerapi.avax.network/x/addresses/7aNfbpAn7qvkeoEW7WHoJRtdBsbrMR2SF

However there are received txs for the same address:
https://explorerapi.avax.network/x/transactions?address=7aNfbpAn7qvkeoEW7WHoJRtdBsbrMR2SF

**Comment by tyler-smith** [comment]
Thanks for the report. This has been fixed.
