### ISSUE TITLE
Indexer service returns error

### ISSUE THREAD

**Issue by Orwelll** [ava-labs/ortelius#41]
Error: ERROR[08-31|09:12:58] /go/src/github.com/ava-labs/ortelius/stream/processor.go#153: Unknown error: context deadline exceeded
![image](https://user-images.githubusercontent.com/46632797/91703976-d0479880-eb9c-11ea-9d55-58c7cc0ad296.png)

**Comment by tyler-smith** [comment]
Thanks. This is actually an expected error so I've changed it to a debug message for clarity.
