### ISSUE TITLE
Unknown Tx Shows up in Explorer

### ISSUE THREAD

**Issue by aaronbuchwald** [ava-labs/ortelius#43]
This transaction shows up as unknown when requesting its status from a bootstrapped node: 2quRTmhcevcUhiMX8As42Y5wrapet4W2qxhhtQibWGM6AtpPrv
```
dhcp-vl2042-15972:gecko aaronbuchwald$ curl -X POST --data '{
>     "jsonrpc":"2.0",
>     "id"     :1,
>     "method" :"avm.getTxStatus",
>     "params" :{
>         "txID":"2quRTmhcevcUhiMX8As42Y5wrapet4W2qxhhtQibWGM6AtpPrv"
>     }
> }' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X
{"jsonrpc":"2.0","result":{"status":"Unknown"},"id":1}
dhcp-vl2042-15972:gecko aaronbuchwald$ 
```

The explorer displays the transaction at this link: https://explorer.avax.network/tx/2quRTmhcevcUhiMX8As42Y5wrapet4W2qxhhtQibWGM6AtpPrv

**Comment by tasinco** [comment]
In function (ingestCreateAssetTx): https://github.com/ava-labs/ortelius/blob/657bb7f160dcf2d56ae97dcb7412ea1929373989/services/indexes/avm/db_writers.go#L155

 tx.ID().String() resolves to -> 'FsXpUrCnioEyjiwPQLN4HLruiRFW4wHao7SYUs1dT34J6BHQ9'  (txid in full below).

But we compute the txID a few lines later:
https://github.com/ava-labs/ortelius/blob/657bb7f160dcf2d56ae97dcb7412ea1929373989/services/indexes/avm/db_writers.go#L160

`wrappedTxBytes, err := db.vm.Codec().Marshal(&avm.Tx{UnsignedTx: tx}) ...	txID := ids.NewID(hashing.ComputeHash256Array(wrappedTxBytes))`

And txID produces -> '2quRTmhcevcUhiMX8As42Y5wrapet4W2qxhhtQibWGM6AtpPrv'


`0x0000000000010000000461258421397c0235bd6d67812a8b2c1cf33929500a7f6916bb2fc4ac646ac091000000016870b7d66ac32540311379e5b5dbad28ec7eb8ddbfc8f4d67299ebb48475907a000000070000000000895440000000000000000000000001000000016f14109c5405d5c53897d839eeef471873bcf13600000001242a194c1e285579d357e54ab9e567c836dfbd928d6af10a9287eac598b1bebd000000006870b7d66ac32540311379e5b5dbad28ec7eb8ddbfc8f4d67299ebb48475907a0000000500000000009896800000000100000000000000000007457861686173680003455841000000000100000000000000010000000700000000000000d2000000000000000000000001000000016f14109c5405d5c53897d839eeef471873bcf136000000010000000900000001a4b6988850665ce76db8ebaf2c5e90f467b13e1642371aee4bc6bfff9cb3cbbe529cb25c049df607b6b836c507d28600ae10b829f6c5aa9b9307581eb5250f9b01`

**Comment by tasinco** [comment]
@tyler-smith that seems like we compute the wrong txID for the create ?
