### ISSUE TITLE
Weird result when using the api to fetch CChain transactions

### ISSUE THREAD

**Issue by tbrunain** [ava-labs/ortelius#432]
I was having a look at the documentation for Ortelius, and while testing [this query](https://docs.avax.network/build/tools/ortelius#list-c-chain-transactions) I got some weird results .

First it only yielded 500 errors, then it suddenly started to give back a response, but with unexpected results.

You can see in the screenshot below that the blocknumber of the first transaction we get is out of the range we passed as an input.

![image](https://user-images.githubusercontent.com/29312251/129483368-7bf55d03-36e5-45ee-b485-4302ba52208d.png)

Here you can see that the start time is ... weird ?

![image](https://user-images.githubusercontent.com/29312251/129483382-cf423eda-728d-41d8-b976-8d81cab8c7c5.png)

**Comment by tasinco** [comment]
We will timeout when a query takes more than 10 seconds.   The query was wrong probably leading to reading a bunch of data, and then causing a timeout.  After a few attempts, the db might of cached enough to answer the query in time..

The issue with the block range should be resolved now.  That's on prod..

The start time and end time come from the query params.  And you didn't pass in those arguments.  So start time is effectively 0, end time is the timestamp of the latest record in the db.  They don't represent anything else in the case for this endpoint.
