### ISSUE TITLE
Enhance /assets endpoint with aggregation data

### ISSUE THREAD

**Issue by strictlymomo** [ava-labs/ortelius#45]
In the Avalanche Explorer, an asset map is necessary for: 
- parsing asset IDs in utxos, transactions, and address balances

When each asset in the asset map is enhanced with metrics, we can describe the activity on a chain through:
- ordered lists, where assets are sorted by a metric
- tallies (e.g. volume) and descriptive statistics (e.g. avg), which are calculated across assets

Currently, the Explorer FE accomplishes this by:
- recursively calling `/assets?offset=...?limit=...`, to get a full map of indexed assets
- calling `/x/transactions/aggregates?assetID=...` for each asset to get its metrics

How can we improve load times of this information? 

I propose to enhance `/assets` or create a new endpoint with aggregation data for each asset. The response would include aggregation data for fixed time periods like 1d, 1m, 1y,  etc.

```
"aggregates": {
   "1d": {
        startTime: "2020-09-02T14:52:59.874Z"
        endTime: "2020-09-03T14:52:59.874Z" 
        addressCount: 0
        assetCount: 0
        outputCount: 0
        transactionCount: 0
        transactionVolume: "0"
   },
   "1m": {...},
    "1y": {...}
}
```
The time periods could be scheduled on a job by the backend or specified by the request.

**Comment by tasinco** [comment]
tracked in AP-89
