### ISSUE TITLE
Duplicate txs

### ISSUE THREAD

**Issue by strictlymomo** [ava-labs/ortelius#51]
Saw a bunch of dups appear in the transactions endpoint around 2020-08-31 at 8 25 19 PM.

![Screen Shot 2020-08-31 at 8 25 19 PM](https://user-images.githubusercontent.com/8671427/92401806-6aa75f00-f0fc-11ea-8a43-a06b9133cf65.png)

Example ID: `2jBHZ8fb8LfeCdSGyNwWw2yrKRyeNeLZ7DUDPVKD6hbTTbs5ea`

**Comment by tyler-smith** [comment]
Duplicate of #36, closing to consolidate.
