### ISSUE TITLE
Withdraw order

### ISSUE THREAD

**Issue by kuropsis** [ava-labs/ortelius#87]
I have withdraw AVAX from binance to my AVAX vallet. It seems in PROCESS for 1 days. When i connect to the Binance Support they said it is related with AVAX blockchain.

Information is as below:
AVAX	
Processing
2687.0068	2020-09-24 12:18:53	
Address: 
X-avax1em3dqvxglyxavtyt5zplyk4fl0tmqpszldwvyx
TxID: 
LAwKv7p7UQ1xZsHJTQqaqamK1MGEpDZB3DGswX5cs6dwnb9HH

**Comment by collincusce** [comment]
This is a problem on Binance's side, not ours. We are working with Binance to assist them in their integration issues. It is best you continue to interact with Binance support until your issue is resolved.
