### ISSUE TITLE
TWEAK: Don't dress Genesis

### ISSUE THREAD

**Issue by tyler-smith** [ava-labs/ortelius#89]
Genesis is special both in that it's "well known" (hardcoded in avalanchego) and it's huge (~1.4MB). We don't show it's details in the explorer in most places because of this and adding this data to any query that returns Genesis is just wasted.

We should have a special flag/endpoint to make Genesis available but we should not dress it otherwise.

**Comment by tasinco** [comment]
tracked in AP-101
