### ISSUE TITLE
Why I got an fuji address on ortelius X chain request 

### ISSUE THREAD

**Issue by yasemincirt** [ava-labs/ortelius#92]
Hi everyone,

I send a request for createAddress method via Ortelius Standalone mode. 

I'm using this commands: 

`curl -X POST --data '{
    "jsonrpc": "2.0",
    "method": "avm.createAddress",
    "params": {
        "username":"myUsername",
        "password":"myPassword"
    },
    "id": 1
}' -H 'content-type:application/json;' 127.0.0.1:9650/ext/bc/X`

I use "/ext/bc/X" for the request url. (I would like the X Chain address) but I got an fuji testnet address after the request.  (like this: "X-fuji1njlfwas3queakekdgf6jcv30wux249xjx5n6k7")

Why? 

how can I set parameter for X chain address?

thank you

**Comment by tasinco** [comment]
See answer on: https://github.com/ava-labs/ortelius/issues/84

**Comment by yasemincirt** [comment]
hi, 

thank you for your response. I set the network_id parameter as` "network_id=5"` on docker-compose.yml  file. and then I send the request via avm.getBalance method to network. But I got this error: 
`{
    "jsonrpc": "2.0",
    "error": {
        "code": -32000,
        **"message": "problem parsing address 'X-avax1ycjrxw42tg4q35rrcs4q52t0eny663hlpq2tw8': expected hrp \"fuji\" but got \"avax\"",**
        "data": null
    },
    "id": 1
}`

Also the request is that: 
`{
    "jsonrpc":"2.0",
    "id"     : 1,
    "method" :"avm.getAllBalances",
    "params" :{
        "address":"X-avax1ycjrxw42tg4q35rrcs4q52t0eny663hlpq2tw8"
    }
}`

how should I fix this?

thank you

**Comment by tasinco** [comment]
I had a typo in the answer.  Mainnet is is network-id=1..

Docker-compose uses local paths to maintain it's db..
https://github.com/ava-labs/ortelius/blob/b2b90c7d97a42acf083ce197eee7e97173fa9e4c/docker/standalone/docker-compose.yml#L23

If you swap the network-id, you might have to do a cleanup.

You can read up on [docker-compose](https://docs.docker.com/compose/)
