### ISSUE TITLE
get transaction response for different tx id

### ISSUE THREAD

**Issue by yasemincirt** [ava-labs/ortelius#93]
Hi,

I send a request via `/x/transactions/:id` on ortelius to FujiTestnet. I gave an TXID this method of Fuji.  - and another tx id- but I got the same response in every request like this: 

`{
    "count": 1,
    "transactions": [
        {
            "id": "FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z",
            "chainID": "2oYMBNV4eNHyqk2fjjV5nVQLDbtmNJzq5s3qs3Lo6ftnC6FByM",
            "type": "create_asset",
            "inputs": null,
            "outputs": [
                {
                    "id": "RgbFSG3d2RfK3KmmMF5LkY8zFEmgKh724Mrg96yw3Z2ksbBqb",
                    "transactionID": "FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z",
                    "outputIndex": 2766,
                    "assetID": "FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z",
                    "outputType": 7,
                    "amount": "2698470588235",
                    "locktime": 0,
                    "threshold": 1,
                    "addresses": [
                        "avax1ww2qmnuzxzg5tzhljj60xc2h9avptdej4s57nv"
                    ],
                    "timestamp": "2020-09-10T00:00:00Z",
                    "redeemingTransactionID": ""
                },
                {
                    "id": "2WfS9HHBUhnGoyzUVt9p2euEBFpr8EFRPpb9xo381ryBZWPnKk",
                    "transactionID": "FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z",
                    "outputIndex": 286,
                    "assetID": "FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z",
                    "outputType": 7,
                    "amount": "39900000000",
                    "locktime": 0,
                    "threshold": 1,
                    "addresses": [
                        "avax15th7g8s42dzr003ehc79n934fktn3f45559lux"
                    ],
                    "timestamp": "2020-09-10T00:00:00Z",
                    "redeemingTransactionID": ""
                },
                {
                    "id": "sSe23trxC7kQusKRzUq8dMc65qbdek7AnosYYET2ifKiShT7Z",
                    "transactionID": "FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z",
                    "outputIndex": 704,
                    "assetID": "FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z",
                    "outputType": 7,
                    "amount": "192600000000",
                    "locktime": 0,
                    "threshold": 1,
                    "addresses": [
                        "avax1quu4vj5vna0ujawam5dv5zjxsjhymcpt5up3w6"
                    ],
                    "timestamp": "2020-09-10T00:00:00Z",
                    "redeemingTransactionID": ""
                },
                {
                    "id": "2e5XAaDb5X8J7JbH9atfSzWvoAguR9vT6NJHhXzsV7SmVbNue7",
                    "transactionID": "FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z",
                    "outputIndex": 1501,
                    "assetID": "FvwEAhmxKfeiG8SnEvq42hc6whRyY3EFYAvebMqDNDGCgxN5Z",
                    "outputType": 7,
                    "amount": "1000100000000",
                    "locktime": 0,
                    "threshold": 1,
                    "addresses": [
                        "avax1ryvxr2zvzptlwmpdawgsawl8vev0uduch4sjjs"
                    ],
                    "timestamp": "2020-09-10T00:00:00Z",
                    "redeemingTransactionID": ""
                },......
`
how is it fix?

Also my request is that: 

`http://0.0.0.0:8080/X/transactions/:2qdDV39k1SoxMnius2fFUEtaRn12iHUuyFjbH8QyFnf4PYyjCc`

response is not mine tx id... why?

also I set the "network_id =5"  and I set the  chainId as `2JVSBoinj9C2J33VntvzYtVJNZdN2NKiwwKjcumHUWEb5DbBrm` (the Fuji network XChain Id. but response chainId is Mainnet XChain Id) in the standalone docker_compose.yml .

 

thank you

**Comment by tasinco** [comment]
`:id` is the param.

`/X/transactions/2qdDV39k1SoxMnius2fFUEtaRn12iHUuyFjbH8QyFnf4PYyjCc`

Don't add the colon.

**Comment by yasemincirt** [comment]
hi,
i tried as yours, but the response turns as a null

**Comment by tasinco** [comment]
This would indicate that there is no txid = 2qdDV39k1SoxMnius2fFUEtaRn12iHUuyFjbH8QyFnf4PYyjCc in your db.

**Comment by yasemincirt** [comment]
oh my god! I checked my db really it is! How do I get the data from Fuji for this db?

**Comment by tasinco** [comment]
ortelius is setup to consume x-chain.  we are working on p-chain.

I would suggest you wipe your setup and re-index.  I noted in a previous request that you need to make sure you have your setup correctly.

For fuji ensure to use network-id=5 and x-chain=2JVSBoinj9C2J33VntvzYtVJNZdN2NKiwwKjcumHUWEb5DbBrm

And remember the node and ortelius must both be setup correctly.

**Comment by tasinco** [comment]
Our avalabs discord is a good place for general help and troubleshooting.  In fact someone just now asked the same question you had above.
People are reasonably active there and willing to help out.  The problem you are facing is not a coding bug..

You can connect to discord from https://www.avalabs.org/


I would suspect that you are just facing a configuration issue.
