### ISSUE TITLE
why ortelius db empty?

### ISSUE THREAD

**Issue by yasemincirt** [ava-labs/ortelius#94]
hi,
I install the ortelius on my machine in that: 

```
> git clone https://github.com/ava-labs/ortelius.git $GOPATH/github.com/ava-labs/ortelius
> make dev_env_start
> make standalone_run 
``` 

and then I checked the ortelius db like that: 

```

mysql> use ortelius;
mysql> show tables;
Empty set (0.00 sec)

```

there is no table in ortelius db. Why?

also I changed the ortelius_standalone, dev_env_mysql_1 , standalone_avalanche default ports, because i used their defaults ports for another containers:

**- avaplatform/avalanchego:v1.0.0 : 9651/tcp, 0.0.0.0:9651->9650/tcp
- avaplatform/ortelius:516bb13 :  0.0.0.0:8081->8080/tcp
- redis:6.0.5-alpine3.12 : 0.0.0.0:6380->6379/tcp
-  dev_env_mysql_1 : 33060/tcp, 0.0.0.0:3307->3306/tcp**

I updated this new ports&hosts in all project documents.  Am I making a mistake because I don't use those default ports?

if not so, what should I do for fix?

thank you

**Comment by tasinco** [comment]
If you change a bunch of ports than the defaults will stop working.

I suspect ortelius is unable to connect to the db anymore. 

You can override your docker-compose settings to get around this issue.  Will continue the conversation in Discord...
